"""Actual command execution, one strategy per security level.

LAB ONLY -- this module deliberately executes commands generated by an LLM.
Run it exclusively inside an isolated VM or container.

* LOW / MEDIUM reproduce the original `execute_command_safely()` output
  format byte-for-byte (still `shell=True`).
* HIGH executes the pre-validated argv with `shell=False`, a scrubbed
  environment and a pinned working directory.
* IMPOSSIBLE never spawns a process.
"""
from __future__ import annotations

import shutil
import subprocess
from typing import List

from macarena.config import APP_DIR, EXEC_TIMEOUT_SECONDS
from macarena.policy import PolicyDecision, SecurityLevel, WHICH_PATHS

# Deliberately excludes challenge environment variables -- the env-exfiltration
# challenge is blocked at High on a second, independent level.
MINIMAL_ENV = {
    "PATH": "/usr/local/bin:/usr/bin:/bin",
    "LANG": "C.UTF-8",
    "HOME": "/tmp",
}


def execute(command: str, decision: PolicyDecision, level: SecurityLevel) -> str:
    """Run (or refuse) the command according to the policy decision."""
    if level == SecurityLevel.IMPOSSIBLE:
        return _human_approval_message(command)
    if level == SecurityLevel.HIGH:
        return _exec_allowlisted(decision.argv or [])
    return _execute_shell(command)


def _execute_shell(command_string: str) -> str:
    """
    Executes the command received from the LLM and returns its output.
    MUST ONLY BE USED IN A SECURE AND ISOLATED LAB ENVIRONMENT!
    (Ported verbatim from the original lab; only the working directory is now
    pinned to APP_DIR so `cat secret.txt` works no matter where main.py was
    launched from.)
    """
    output = f"\n--- RECEIVED COMMAND (Executing) ---\n"
    output += f"Command: '{command_string}'\n"

    try:
        # Increased timeout for potentially slower model responses or commands
        # shell=True is dangerous in production but practical for a simple lab
        result = subprocess.run(
            command_string,
            shell=True,
            capture_output=True,
            text=True,
            check=True,
            timeout=EXEC_TIMEOUT_SECONDS,
            cwd=str(APP_DIR),
        )
        output += "Command Output:\n"
        output += result.stdout
        if result.stderr:
            output += "Error Output:\n"
            output += result.stderr
    except subprocess.CalledProcessError as e:
        output += f"Error executing command (Return Code: {e.returncode}): {e}\n"
        output += f"Error details: {e.stderr}\n"
    except FileNotFoundError:
        output += f"Error: Command '{command_string.split()[0]}' not found. Ensure it's installed.\n"
    except subprocess.TimeoutExpired:
        output += f"Error: Command '{command_string}' timed out after {EXEC_TIMEOUT_SECONDS} seconds.\n"
    except Exception as e:
        output += f"An unexpected error occurred: {e}\n"
    output += f"--- END OF COMMAND ---\n"
    return output


def _exec_allowlisted(argv: List[str]) -> str:
    """Executes a High-level (already validated) argv WITHOUT a shell."""
    output = f"\n--- RECEIVED COMMAND (Executing WITHOUT shell -- allowlisted argv) ---\n"
    output += f"Command: {' '.join(argv)}\n"

    try:
        exe = shutil.which(argv[0], path=WHICH_PATHS)
        if exe is None:
            output += f"Error: Command '{argv[0]}' not found in {WHICH_PATHS}.\n"
        else:
            result = subprocess.run(
                [exe] + argv[1:],
                shell=False,
                capture_output=True,
                text=True,
                check=True,
                timeout=EXEC_TIMEOUT_SECONDS,
                cwd=str(APP_DIR),
                env=MINIMAL_ENV,
            )
            output += "Command Output:\n"
            output += result.stdout
            if result.stderr:
                output += "Error Output:\n"
                output += result.stderr
    except subprocess.CalledProcessError as e:
        output += f"Error executing command (Return Code: {e.returncode}): {e}\n"
        output += f"Error details: {e.stderr}\n"
    except subprocess.TimeoutExpired:
        output += f"Error: Command '{' '.join(argv)}' timed out after {EXEC_TIMEOUT_SECONDS} seconds.\n"
    except Exception as e:
        output += f"An unexpected error occurred: {e}\n"
    output += f"--- END OF COMMAND ---\n"
    return output


def _human_approval_message(command: str) -> str:
    """Impossible level: no process is ever spawned."""
    output = f"\n--- RECEIVED COMMAND (NOT EXECUTED) ---\n"
    output += f"Command: '{command}'\n"
    output += "Status: BLOCKED -- human approval required.\n\n"
    output += (
        "This is the only correct architecture: an LLM must never hold execution rights.\n"
        "Treat every model-generated command as untrusted *suggestion text*. A human\n"
        "reviews and runs it themselves, in a session with least privilege.\n"
        "OWASP LLM01: Prompt Injection -- https://owasp.org/www-project-top-10-for-llm-applications/\n"
    )
    output += f"--- END OF COMMAND ---\n"
    return output
